version: "3"

services:
  
  flask-web:
    build:
      context: .
      dockerfile: Dockerfile
    # image: python:3.7.0-alpine3.8
    environment:
      - PYTHONBUFFERED=1
    ports:
      - "5000:5000"
  
  redis:
    image: redis:4.0.11-alpine
    