apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: todo-flask-react
build:
  artifacts:
    - image: flask-k8s
      context: backend
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - backend/deployment.yaml
