apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-express
spec:
  selector:
    matchLabels:
      app: graphql-express
  template:
    metadata:
      labels:
        app: graphql-express
    spec:
      containers:
      - name: graphql-express
        image: graphql-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: graphql-express
spec:
  type: LoadBalancer
  selector:
    app: graphql-express
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001

