apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: graphql-express

build:
  artifacts:
    - image: graphql-express
      context: .
      docker:
        dockerfile: Dockerfile
        
deploy:
  kubectl:
    manifests:
      # SYNC:/app:/src -n graphql-express
      - "graphql-k8s.yml"
