apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: flask-mongo
build:
  artifacts:
    - image: flask-api
      context: api
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    
    # JWT Identity Provider
    - identity_provider/db/postgres-config.yaml
    - identity_provider/db/postgres-pvc-pv.yaml
    - identity_provider/db/postgres-k8s.yaml
    - identity_provider/supert-tokens-k8s.yaml

    # API
    - api/api-k8s.yaml
    
    # FRONTEND
    # - frontend/frontend-k8s.yaml
    
    # MONGO
    # - db/mongo-secret.yaml
    # - db/mongodb-k8s.yaml
    # - db/mongo-express-configmap.yaml
    # - db/mongo-express-k8s.yaml
