# This is only used to do thinkgs like generating migrations, etc..

version: "3.8"

services:
  
  api:
    build:
      context: ./flask-api
      target: dev
    environment:
      - DB_URL=postgresql://user:pass@localhost:5431/app-db
    volumes:
      - ./flask-api:/usr/src/app:rw
    ports:
      - 5000:5000

  db:
    image: postgres:alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app-db
    ports:
      - 5431:5431
