apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: flask-postgres-deployment
build:
  artifacts:
  - image: flask-api
    context: ./flask-api
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: "flask-apy/"
          dest: .


deploy:
  kubectl:
    manifests:
    - configMap.yml
    - secrets.yml
    - postgres-k8s.yml
    - flask-api/deployment.yml
