"""Create ponies

Revision ID: b220137c78b1
Revises: b15480a60b4d
Create Date: 2022-07-16 03:36:57.083091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b220137c78b1'
down_revision = 'b15480a60b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('owners_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owners_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pony')
    # ### end Alembic commands ###
