version: "3.8"

services:

  catalog-management:
    build:
      context: ./backend/catalog-management # The "root directory" for this image.
      target: dev
    ports:
      - 8081:8081
    volumes:
      - ./backend/catalog-management:/app:delegated
      - /app/node_modules
